package org.sjtu.p615.entity;

// Generated 2014-9-21 11:55:16 by Hibernate Tools 3.4.0.CR1

/**
 * UserProjectId generated by hbm2java
 */
public class UserProjectId implements java.io.Serializable {

	private int userId;
	private String projectName;
	private String role;

	public UserProjectId() {
	}

	public UserProjectId(int userId, String projectName, String role) {
		this.userId = userId;
		this.projectName = projectName;
		this.role = role;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserProjectId))
			return false;
		UserProjectId castOther = (UserProjectId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getProjectName() == castOther.getProjectName()) || (this
						.getProjectName() != null
						&& castOther.getProjectName() != null && this
						.getProjectName().equals(castOther.getProjectName())))
				&& ((this.getRole() == castOther.getRole()) || (this.getRole() != null
						&& castOther.getRole() != null && this.getRole()
						.equals(castOther.getRole())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37
				* result
				+ (getProjectName() == null ? 0 : this.getProjectName()
						.hashCode());
		result = 37 * result
				+ (getRole() == null ? 0 : this.getRole().hashCode());
		return result;
	}

}
