package org.sjtu.p615.entity;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.Calendar;

// default package
// Generated 2014-10-9 13:34:52 by Hibernate Tools 3.4.0.CR1

/**
 * Planoutput generated by hbm2java
 */
public class Planoutput implements java.io.Serializable {

	private Integer planOutputCode;
	private String filePath;
	private boolean deleteMark;
	private String taskCode;
	private String fileName;
	private Timestamp uploadDate;
	
	private String fileHref;
	private String fileDelHref;
	private String UUID;
	private String uploadDateString;
	
	

	public Planoutput() {
	}

	public Planoutput(String filePath, boolean deleteMark, String taskCode,
			String fileName) {
		this.filePath = filePath;
		this.deleteMark = deleteMark;
		this.taskCode = taskCode;
		this.fileName = fileName;
		 
	}

	public Integer getPlanOutputCode() {
		return this.planOutputCode;
	}

	public void setPlanOutputCode(Integer planOutputCode) {
		this.planOutputCode = planOutputCode;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public boolean isDeleteMark() {
		return this.deleteMark;
	}

	public void setDeleteMark(boolean deleteMark) {
		this.deleteMark = deleteMark;
	}

	public String getTaskCode() {
		return this.taskCode;
	}

	public void setTaskCode(String taskCode) {
		this.taskCode = taskCode;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFileHref() {
		return fileHref;
	}

	public void setFileHref(String fileHref) {
		this.fileHref = fileHref;
	}
	
	public String getUUID() {
		return UUID;
	}

	public void setUUID(String uUID) {
		UUID = uUID;
	}

	public String getFileDelHref() {
		return fileDelHref;
	}

	public void setFileDelHref(String fileDelHref) {
		this.fileDelHref = fileDelHref;
	}

	public Timestamp getUploadDate() {
		return uploadDate;
	}

	public void setUploadDate(Timestamp uploadDate) {
		this.uploadDate = uploadDate;
	}

	public String getUploadDateString() {
		return uploadDateString;
	}

	public void setUploadDateString(String uploadDateString) {
		this.uploadDateString = uploadDateString;
	}

	

}
