package org.sjtu.p615.entity;

// default package
// Generated 2014-11-27 15:14:10 by Hibernate Tools 3.4.0.CR1

/**
 * Fracasprivilege generated by hbm2java
 */
public class Fracasprivilege implements java.io.Serializable {

	private int roleId;
	private Boolean inputReport;
	private Boolean techOpinion;
	private Boolean qualityOpinion;
	private Boolean mrbOpinion;
	private Boolean dutyOpinion;
	private Boolean deleteMark;

	public Fracasprivilege() {
	}

	public Fracasprivilege(int roleId) {
		this.roleId = roleId;
	}

	public Fracasprivilege(int roleId, Boolean inputReport,
			Boolean techOpinion, Boolean qualityOpinion, Boolean mrbOpinion,
			Boolean dutyOpinion, Boolean deleteMark) {
		this.roleId = roleId;
		this.inputReport = inputReport;
		this.techOpinion = techOpinion;
		this.qualityOpinion = qualityOpinion;
		this.mrbOpinion = mrbOpinion;
		this.dutyOpinion = dutyOpinion;
		this.deleteMark = deleteMark;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public Boolean getInputReport() {
		return this.inputReport;
	}

	public void setInputReport(Boolean inputReport) {
		this.inputReport = inputReport;
	}

	public Boolean getTechOpinion() {
		return this.techOpinion;
	}

	public void setTechOpinion(Boolean techOpinion) {
		this.techOpinion = techOpinion;
	}

	public Boolean getQualityOpinion() {
		return this.qualityOpinion;
	}

	public void setQualityOpinion(Boolean qualityOpinion) {
		this.qualityOpinion = qualityOpinion;
	}

	public Boolean getMrbOpinion() {
		return this.mrbOpinion;
	}

	public void setMrbOpinion(Boolean mrbOpinion) {
		this.mrbOpinion = mrbOpinion;
	}

	public Boolean getDutyOpinion() {
		return this.dutyOpinion;
	}

	public void setDutyOpinion(Boolean dutyOpinion) {
		this.dutyOpinion = dutyOpinion;
	}

	public Boolean getDeleteMark() {
		return this.deleteMark;
	}

	public void setDeleteMark(Boolean deleteMark) {
		this.deleteMark = deleteMark;
	}

}
