package org.sjtu.p615.entity;

// default package
// Generated 2014-9-27 21:50:52 by Hibernate Tools 3.4.0.CR1

/**
 * Script generated by hbm2java
 */
public class Script implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer scriptKey;
	private String employeeId;
	private String scriptContent;
	private String scriptType;
	private String uuid;

	public Script() {
	}

	public Script(String employeeId, String scriptContent) {
		this.employeeId = employeeId;
		this.scriptContent = scriptContent;
	}

	public Integer getScriptKey() {
		return this.scriptKey;
	}

	public void setScriptKey(Integer scriptKey) {
		this.scriptKey = scriptKey;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public String getScriptContent() {
		return this.scriptContent;
	}

	public void setScriptContent(String scriptContent) {
		this.scriptContent = scriptContent;
	}

	public String getScriptType() {
		return scriptType;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public void setScriptType(String scriptType) {
		this.scriptType = scriptType;
	}



}
