package org.sjtu.p615.entity;

// default package
// Generated 2015-6-1 14:18:11 by Hibernate Tools 3.4.0.CR1

/**
 * Amprivilege generated by hbm2java
 */
public class Amprivilege implements java.io.Serializable {

	private int roleId;
	private String roleName;
	private Integer index;
	private Integer prjOverview;
	private Integer createPrj;
	private Integer grpMaintain;
	private Integer addPlan;
	private Integer publishPlan;
	private Integer changePlan;
	private Integer auditPlanChange;
	private Integer planChangeImplement;
	private Integer resolveTask;
	private Integer publishTask;
	private Integer feedBackTask;
	private Integer readPlan;
	private Integer statistics;
	private Integer addActionDir;
	private Integer publishActionDir;
	private Integer addAction;
	private Integer publishAction;
	private Integer feedBackAction;
	private Integer auditAction;
	private Integer readAction;
	private Integer commMgm;
	private Integer templateMaintain;
	private Integer downloadTemplate;
	private Integer importPlan;
	private Integer exportPlan;
	private Integer addProject;
	private Integer addGroup;
	private Integer addGroupMember;
	private Boolean deleteMark;

	public Amprivilege() {
		
		this.addAction=0;
		this.addActionDir=0;
		this.addGroup=0;
		this.addGroupMember=0;
		this.addPlan=0;
		this.addProject=0;
		this.auditAction=0;
		this.auditPlanChange=0;
		this.changePlan=0;
		this.commMgm=0;
		this.createPrj=0;
		this.deleteMark=false;
		this.downloadTemplate=0;
		this.exportPlan=0;
		this.feedBackAction=0;
		this.feedBackTask=0;
		this.grpMaintain=0;
		this.importPlan=0;
		this.index=0;
		this.planChangeImplement=0;
		this.prjOverview=0;
		this.publishAction=0;
		this.publishActionDir=0;
		this.publishPlan=0;
		this.publishTask=0;
		this.readAction=0;
		this.readPlan=0;
		this.resolveTask=0;
		this.statistics=0;
		this.templateMaintain=0;
	}

	public Amprivilege(int roleId) {
		this.roleId = roleId;
	}

	public Amprivilege(int roleId, String roleName, Integer index,
			Integer prjOverview, Integer createPrj, Integer grpMaintain,
			Integer addPlan, Integer publishPlan, Integer changePlan,
			Integer auditPlanChange, Integer planChangeImplement,
			Integer resolveTask, Integer publishTask, Integer feedBackTask,
			Integer readPlan, Integer statistics, Integer addActionDir,
			Integer publishActionDir, Integer addAction, Integer publishAction,
			Integer feedBackAction, Integer auditAction, Integer readAction,
			Integer commMgm, Integer templateMaintain,
			Integer downloadTemplate, Integer importPlan, Integer exportPlan,
			Integer addProject, Integer addGroup, Integer addGroupMember,
			Boolean deleteMark) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.index = index;
		this.prjOverview = prjOverview;
		this.createPrj = createPrj;
		this.grpMaintain = grpMaintain;
		this.addPlan = addPlan;
		this.publishPlan = publishPlan;
		this.changePlan = changePlan;
		this.auditPlanChange = auditPlanChange;
		this.planChangeImplement = planChangeImplement;
		this.resolveTask = resolveTask;
		this.publishTask = publishTask;
		this.feedBackTask = feedBackTask;
		this.readPlan = readPlan;
		this.statistics = statistics;
		this.addActionDir = addActionDir;
		this.publishActionDir = publishActionDir;
		this.addAction = addAction;
		this.publishAction = publishAction;
		this.feedBackAction = feedBackAction;
		this.auditAction = auditAction;
		this.readAction = readAction;
		this.commMgm = commMgm;
		this.templateMaintain = templateMaintain;
		this.downloadTemplate = downloadTemplate;
		this.importPlan = importPlan;
		this.exportPlan = exportPlan;
		this.addProject = addProject;
		this.addGroup = addGroup;
		this.addGroupMember = addGroupMember;
		this.deleteMark = deleteMark;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Integer getIndex() {
		return this.index;
	}

	public void setIndex(Integer index) {
		this.index = index;
	}

	public Integer getPrjOverview() {
		return this.prjOverview;
	}

	public void setPrjOverview(Integer prjOverview) {
		this.prjOverview = prjOverview;
	}

	public Integer getCreatePrj() {
		return this.createPrj;
	}

	public void setCreatePrj(Integer createPrj) {
		this.createPrj = createPrj;
	}

	public Integer getGrpMaintain() {
		return this.grpMaintain;
	}

	public void setGrpMaintain(Integer grpMaintain) {
		this.grpMaintain = grpMaintain;
	}

	public Integer getAddPlan() {
		return this.addPlan;
	}

	public void setAddPlan(Integer addPlan) {
		this.addPlan = addPlan;
	}

	public Integer getPublishPlan() {
		return this.publishPlan;
	}

	public void setPublishPlan(Integer publishPlan) {
		this.publishPlan = publishPlan;
	}

	public Integer getChangePlan() {
		return this.changePlan;
	}

	public void setChangePlan(Integer changePlan) {
		this.changePlan = changePlan;
	}

	public Integer getAuditPlanChange() {
		return this.auditPlanChange;
	}

	public void setAuditPlanChange(Integer auditPlanChange) {
		this.auditPlanChange = auditPlanChange;
	}

	public Integer getPlanChangeImplement() {
		return this.planChangeImplement;
	}

	public void setPlanChangeImplement(Integer planChangeImplement) {
		this.planChangeImplement = planChangeImplement;
	}

	public Integer getResolveTask() {
		return this.resolveTask;
	}

	public void setResolveTask(Integer resolveTask) {
		this.resolveTask = resolveTask;
	}

	public Integer getPublishTask() {
		return this.publishTask;
	}

	public void setPublishTask(Integer publishTask) {
		this.publishTask = publishTask;
	}

	public Integer getFeedBackTask() {
		return this.feedBackTask;
	}

	public void setFeedBackTask(Integer feedBackTask) {
		this.feedBackTask = feedBackTask;
	}

	public Integer getReadPlan() {
		return this.readPlan;
	}

	public void setReadPlan(Integer readPlan) {
		this.readPlan = readPlan;
	}

	public Integer getStatistics() {
		return this.statistics;
	}

	public void setStatistics(Integer statistics) {
		this.statistics = statistics;
	}

	public Integer getAddActionDir() {
		return this.addActionDir;
	}

	public void setAddActionDir(Integer addActionDir) {
		this.addActionDir = addActionDir;
	}

	public Integer getPublishActionDir() {
		return this.publishActionDir;
	}

	public void setPublishActionDir(Integer publishActionDir) {
		this.publishActionDir = publishActionDir;
	}

	public Integer getAddAction() {
		return this.addAction;
	}

	public void setAddAction(Integer addAction) {
		this.addAction = addAction;
	}

	public Integer getPublishAction() {
		return this.publishAction;
	}

	public void setPublishAction(Integer publishAction) {
		this.publishAction = publishAction;
	}

	public Integer getFeedBackAction() {
		return this.feedBackAction;
	}

	public void setFeedBackAction(Integer feedBackAction) {
		this.feedBackAction = feedBackAction;
	}

	public Integer getAuditAction() {
		return this.auditAction;
	}

	public void setAuditAction(Integer auditAction) {
		this.auditAction = auditAction;
	}

	public Integer getReadAction() {
		return this.readAction;
	}

	public void setReadAction(Integer readAction) {
		this.readAction = readAction;
	}

	public Integer getCommMgm() {
		return this.commMgm;
	}

	public void setCommMgm(Integer commMgm) {
		this.commMgm = commMgm;
	}

	public Integer getTemplateMaintain() {
		return this.templateMaintain;
	}

	public void setTemplateMaintain(Integer templateMaintain) {
		this.templateMaintain = templateMaintain;
	}

	public Integer getDownloadTemplate() {
		return this.downloadTemplate;
	}

	public void setDownloadTemplate(Integer downloadTemplate) {
		this.downloadTemplate = downloadTemplate;
	}

	public Integer getImportPlan() {
		return this.importPlan;
	}

	public void setImportPlan(Integer importPlan) {
		this.importPlan = importPlan;
	}

	public Integer getExportPlan() {
		return this.exportPlan;
	}

	public void setExportPlan(Integer exportPlan) {
		this.exportPlan = exportPlan;
	}

	public Integer getAddProject() {
		return this.addProject;
	}

	public void setAddProject(Integer addProject) {
		this.addProject = addProject;
	}

	public Integer getAddGroup() {
		return this.addGroup;
	}

	public void setAddGroup(Integer addGroup) {
		this.addGroup = addGroup;
	}

	public Integer getAddGroupMember() {
		return this.addGroupMember;
	}

	public void setAddGroupMember(Integer addGroupMember) {
		this.addGroupMember = addGroupMember;
	}

	public Boolean getDeleteMark() {
		return this.deleteMark;
	}

	public void setDeleteMark(Boolean deleteMark) {
		this.deleteMark = deleteMark;
	}

}
