package org.sjtu.p615.entity;
// Generated 2015-9-29 15:21:03 by Hibernate Tools 4.0.0

import java.sql.Date;
import java.util.List;

/**
 * Action generated by hbm2java
 */
public class Action implements java.io.Serializable {

	private Integer actionKey;
	private String actionId;
	private String parentActionId;
	private String actionType;
	private String actionName;
	private Date actionStartDate;
	private Date actionDeadlineDate;
	private Date actionFinishDate;
	private Integer actionState;
	private String actionResource;
	private String controllerDepartment;
	private String controllerDepartmentId;
	private String actionController;
	private String actionControllerId;
	private String actionApprover;
	private String actionApproverId;
	private String actionAuditor;
	private String actionAuditorId;
	private String actionContent;
	private String actionOutput;
	private String remark;
	private String employeeId;
	private String projectId;
	private String projectName;
	private Boolean back;
	private Byte leaf;
	private Integer level;
	private Boolean deleteMark;
	
	private List<Planoutput> planoutput;

	public List<Planoutput> getPlanoutput() {
		return planoutput;
	}

	public void setPlanoutput(List<Planoutput> planoutput) {
		this.planoutput = planoutput;
	}

	public Action() {
	}

	public Action(String actionId) {
		this.actionId = actionId;
	}

	public Action(String actionId, String parentActionId, String actionType,
			String actionName, Date actionStartDate, Date actionDeadlineDate,
			Date actionFinishDate, Integer actionState, String actionResource,
			String controllerDepartment, String controllerDepartmentId,
			String actionController, String actionControllerId,
			String actionApprover, String actionApproverId,
			String actionAuditor, String actionAuditorId, String actionContent,
			String actionOutput, String remark, String employeeId,
			String projectId, String projectName, Boolean back, Byte leaf,
			Integer level, Boolean deleteMark) {
		this.actionId = actionId;
		this.parentActionId = parentActionId;
		this.actionType = actionType;
		this.actionName = actionName;
		this.actionStartDate = actionStartDate;
		this.actionDeadlineDate = actionDeadlineDate;
		this.actionFinishDate = actionFinishDate;
		this.actionState = actionState;
		this.actionResource = actionResource;
		this.controllerDepartment = controllerDepartment;
		this.controllerDepartmentId = controllerDepartmentId;
		this.actionController = actionController;
		this.actionControllerId = actionControllerId;
		this.actionApprover = actionApprover;
		this.actionApproverId = actionApproverId;
		this.actionAuditor = actionAuditor;
		this.actionAuditorId = actionAuditorId;
		this.actionContent = actionContent;
		this.actionOutput = actionOutput;
		this.remark = remark;
		this.employeeId = employeeId;
		this.projectId = projectId;
		this.projectName = projectName;
		this.back = back;
		this.leaf = leaf;
		this.level = level;
		this.deleteMark = deleteMark;
	}

	public Integer getActionKey() {
		return this.actionKey;
	}

	public void setActionKey(Integer actionKey) {
		this.actionKey = actionKey;
	}

	public String getActionId() {
		return this.actionId;
	}

	public void setActionId(String actionId) {
		this.actionId = actionId;
	}

	public String getParentActionId() {
		return this.parentActionId;
	}

	public void setParentActionId(String parentActionId) {
		this.parentActionId = parentActionId;
	}

	public String getActionType() {
		return this.actionType;
	}

	public void setActionType(String actionType) {
		this.actionType = actionType;
	}

	public String getActionName() {
		return this.actionName;
	}

	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

	public Date getActionStartDate() {
		return this.actionStartDate;
	}

	public void setActionStartDate(Date actionStartDate) {
		this.actionStartDate = actionStartDate;
	}

	public Date getActionDeadlineDate() {
		return this.actionDeadlineDate;
	}

	public void setActionDeadlineDate(Date actionDeadlineDate) {
		this.actionDeadlineDate = actionDeadlineDate;
	}

	public Date getActionFinishDate() {
		return this.actionFinishDate;
	}

	public void setActionFinishDate(Date actionFinishDate) {
		this.actionFinishDate = actionFinishDate;
	}

	public Integer getActionState() {
		return this.actionState;
	}

	public void setActionState(Integer actionState) {
		this.actionState = actionState;
	}

	public String getActionResource() {
		return this.actionResource;
	}

	public void setActionResource(String actionResource) {
		this.actionResource = actionResource;
	}

	public String getControllerDepartment() {
		return this.controllerDepartment;
	}

	public void setControllerDepartment(String controllerDepartment) {
		this.controllerDepartment = controllerDepartment;
	}

	public String getControllerDepartmentId() {
		return this.controllerDepartmentId;
	}

	public void setControllerDepartmentId(String controllerDepartmentId) {
		this.controllerDepartmentId = controllerDepartmentId;
	}

	public String getActionController() {
		return this.actionController;
	}

	public void setActionController(String actionController) {
		this.actionController = actionController;
	}

	public String getActionControllerId() {
		return this.actionControllerId;
	}

	public void setActionControllerId(String actionControllerId) {
		this.actionControllerId = actionControllerId;
	}

	public String getActionApprover() {
		return this.actionApprover;
	}

	public void setActionApprover(String actionApprover) {
		this.actionApprover = actionApprover;
	}

	public String getActionApproverId() {
		return this.actionApproverId;
	}

	public void setActionApproverId(String actionApproverId) {
		this.actionApproverId = actionApproverId;
	}

	public String getActionAuditor() {
		return this.actionAuditor;
	}

	public void setActionAuditor(String actionAuditor) {
		this.actionAuditor = actionAuditor;
	}

	public String getActionAuditorId() {
		return this.actionAuditorId;
	}

	public void setActionAuditorId(String actionAuditorId) {
		this.actionAuditorId = actionAuditorId;
	}

	public String getActionContent() {
		return this.actionContent;
	}

	public void setActionContent(String actionContent) {
		this.actionContent = actionContent;
	}

	public String getActionOutput() {
		return this.actionOutput;
	}

	public void setActionOutput(String actionOutput) {
		this.actionOutput = actionOutput;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public Boolean getBack() {
		return this.back;
	}

	public void setBack(Boolean back) {
		this.back = back;
	}

	public Byte getLeaf() {
		return this.leaf;
	}

	public void setLeaf(Byte leaf) {
		this.leaf = leaf;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public Boolean getDeleteMark() {
		return this.deleteMark;
	}

	public void setDeleteMark(Boolean deleteMark) {
		this.deleteMark = deleteMark;
	}

}
