package org.sjtu.p615.entity;
// Generated 2015-10-17 17:21:19 by Hibernate Tools 3.4.0.CR1

/**
 * ContractRegist generated by hbm2java
 */
public class ContractRegist implements java.io.Serializable {

	private String id;
	private String name;
	private String moneyFlow;
	private String isOffshore;
	private String description;
	private String contractContain;
	private String moneyType;
	private String department;
	private String operator;
	private String project;
	private String budgetCode;
	private String totalMoney;
	private String currencyType;
	private String performStartDate;
	private String performEndDate;
	private String cooperation;
	private String contractArchive;
	private String payNodeId1;
	private String payNodeId2;
	private String receiveNodeId1;
	private String receiveNodeId2;
	private String preregistRecordCm;
	private String preregistRecordPm;
	private String registRecordCm;
	private String registRecordPm;
	private String payRecord1Cm;
	private String payRecord1Pm;
	private String verifyRecordCm;
	private String verifyRecordPm;
	private String receiveRecord1Cm;
	private String receiveRecord1Pm;

	public ContractRegist() {
	}

	public ContractRegist(String id) {
		this.id = id;
	}

	public ContractRegist(String id, String name, String moneyFlow, String isOffshore, String description,
			String contractContain, String moneyType, String department, String operator, String project,
			String budgetCode, String totalMoney, String currencyType, String performStartDate, String performEndDate,
			String cooperation, String contractArchive, String payNodeId1, String payNodeId2, String receiveNodeId1,
			String receiveNodeId2, String preregistRecordCm, String preregistRecordPm, String registRecordCm,
			String registRecordPm, String payRecord1Cm, String payRecord1Pm, String verifyRecordCm,
			String verifyRecordPm, String receiveRecord1Cm, String receiveRecord1Pm) {
		this.id = id;
		this.name = name;
		this.moneyFlow = moneyFlow;
		this.isOffshore = isOffshore;
		this.description = description;
		this.contractContain = contractContain;
		this.moneyType = moneyType;
		this.department = department;
		this.operator = operator;
		this.project = project;
		this.budgetCode = budgetCode;
		this.totalMoney = totalMoney;
		this.currencyType = currencyType;
		this.performStartDate = performStartDate;
		this.performEndDate = performEndDate;
		this.cooperation = cooperation;
		this.contractArchive = contractArchive;
		this.payNodeId1 = payNodeId1;
		this.payNodeId2 = payNodeId2;
		this.receiveNodeId1 = receiveNodeId1;
		this.receiveNodeId2 = receiveNodeId2;
		this.preregistRecordCm = preregistRecordCm;
		this.preregistRecordPm = preregistRecordPm;
		this.registRecordCm = registRecordCm;
		this.registRecordPm = registRecordPm;
		this.payRecord1Cm = payRecord1Cm;
		this.payRecord1Pm = payRecord1Pm;
		this.verifyRecordCm = verifyRecordCm;
		this.verifyRecordPm = verifyRecordPm;
		this.receiveRecord1Cm = receiveRecord1Cm;
		this.receiveRecord1Pm = receiveRecord1Pm;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMoneyFlow() {
		return this.moneyFlow;
	}

	public void setMoneyFlow(String moneyFlow) {
		this.moneyFlow = moneyFlow;
	}

	public String getIsOffshore() {
		return this.isOffshore;
	}

	public void setIsOffshore(String isOffshore) {
		this.isOffshore = isOffshore;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getContractContain() {
		return this.contractContain;
	}

	public void setContractContain(String contractContain) {
		this.contractContain = contractContain;
	}

	public String getMoneyType() {
		return this.moneyType;
	}

	public void setMoneyType(String moneyType) {
		this.moneyType = moneyType;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getProject() {
		return this.project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	public String getBudgetCode() {
		return this.budgetCode;
	}

	public void setBudgetCode(String budgetCode) {
		this.budgetCode = budgetCode;
	}

	public String getTotalMoney() {
		return this.totalMoney;
	}

	public void setTotalMoney(String totalMoney) {
		this.totalMoney = totalMoney;
	}

	public String getCurrencyType() {
		return this.currencyType;
	}

	public void setCurrencyType(String currencyType) {
		this.currencyType = currencyType;
	}

	public String getPerformStartDate() {
		return this.performStartDate;
	}

	public void setPerformStartDate(String performStartDate) {
		this.performStartDate = performStartDate;
	}

	public String getPerformEndDate() {
		return this.performEndDate;
	}

	public void setPerformEndDate(String performEndDate) {
		this.performEndDate = performEndDate;
	}

	public String getCooperation() {
		return this.cooperation;
	}

	public void setCooperation(String cooperation) {
		this.cooperation = cooperation;
	}

	public String getContractArchive() {
		return this.contractArchive;
	}

	public void setContractArchive(String contractArchive) {
		this.contractArchive = contractArchive;
	}

	public String getPayNodeId1() {
		return this.payNodeId1;
	}

	public void setPayNodeId1(String payNodeId1) {
		this.payNodeId1 = payNodeId1;
	}

	public String getPayNodeId2() {
		return this.payNodeId2;
	}

	public void setPayNodeId2(String payNodeId2) {
		this.payNodeId2 = payNodeId2;
	}

	public String getReceiveNodeId1() {
		return this.receiveNodeId1;
	}

	public void setReceiveNodeId1(String receiveNodeId1) {
		this.receiveNodeId1 = receiveNodeId1;
	}

	public String getReceiveNodeId2() {
		return this.receiveNodeId2;
	}

	public void setReceiveNodeId2(String receiveNodeId2) {
		this.receiveNodeId2 = receiveNodeId2;
	}

	public String getPreregistRecordCm() {
		return this.preregistRecordCm;
	}

	public void setPreregistRecordCm(String preregistRecordCm) {
		this.preregistRecordCm = preregistRecordCm;
	}

	public String getPreregistRecordPm() {
		return this.preregistRecordPm;
	}

	public void setPreregistRecordPm(String preregistRecordPm) {
		this.preregistRecordPm = preregistRecordPm;
	}

	public String getRegistRecordCm() {
		return this.registRecordCm;
	}

	public void setRegistRecordCm(String registRecordCm) {
		this.registRecordCm = registRecordCm;
	}

	public String getRegistRecordPm() {
		return this.registRecordPm;
	}

	public void setRegistRecordPm(String registRecordPm) {
		this.registRecordPm = registRecordPm;
	}

	public String getPayRecord1Cm() {
		return this.payRecord1Cm;
	}

	public void setPayRecord1Cm(String payRecord1Cm) {
		this.payRecord1Cm = payRecord1Cm;
	}

	public String getPayRecord1Pm() {
		return this.payRecord1Pm;
	}

	public void setPayRecord1Pm(String payRecord1Pm) {
		this.payRecord1Pm = payRecord1Pm;
	}

	public String getVerifyRecordCm() {
		return this.verifyRecordCm;
	}

	public void setVerifyRecordCm(String verifyRecordCm) {
		this.verifyRecordCm = verifyRecordCm;
	}

	public String getVerifyRecordPm() {
		return this.verifyRecordPm;
	}

	public void setVerifyRecordPm(String verifyRecordPm) {
		this.verifyRecordPm = verifyRecordPm;
	}

	public String getReceiveRecord1Cm() {
		return this.receiveRecord1Cm;
	}

	public void setReceiveRecord1Cm(String receiveRecord1Cm) {
		this.receiveRecord1Cm = receiveRecord1Cm;
	}

	public String getReceiveRecord1Pm() {
		return this.receiveRecord1Pm;
	}

	public void setReceiveRecord1Pm(String receiveRecord1Pm) {
		this.receiveRecord1Pm = receiveRecord1Pm;
	}

}
