package org.sjtu.p615.entity;

// default package
// Generated 2015-6-24 21:48:24 by Hibernate Tools 3.4.0.CR1

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private Integer id;
	private String name;

	public Department() {
	}

	public Department(String name) {
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
