package org.sjtu.p615.entity;

// default package
// Generated 2015-6-1 14:18:11 by Hibernate Tools 3.4.0.CR1

/**
 * Notice generated by hbm2java
 */
public class Notice implements java.io.Serializable {

	private Integer id;
	private String type;
	private String prjId;
	private String title;
	private String content;
	private String fileName;
	private String path;
	private Integer state;
	private String empId;
	private String downloadHref;
	private String deleteHref;
	private String empName;
	private String prjName;
	public Notice() {
	}

	public Notice(Integer id, String type, String prjId, String title,
			String content, String fileName, String path, Integer state,
			String empId, String downloadHref, String deleteHref,
			String empName, String prjName) {
		super();
		this.id = id;
		this.type = type;
		this.prjId = prjId;
		this.title = title;
		this.content = content;
		this.fileName = fileName;
		this.path = path;
		this.state = state;
		this.empId = empId;
		this.downloadHref = downloadHref;
		this.deleteHref = deleteHref;
		this.empName = empName;
		this.prjName = prjName;
	}

	public String getDownloadHref() {
		return downloadHref;
	}

	public void setDownloadHref(String downloadHref) {
		this.downloadHref = downloadHref;
	}

	public String getDeleteHref() {
		return deleteHref;
	}

	public void setDeleteHref(String deleteHref) {
		this.deleteHref = deleteHref;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}



	public String getPrjId() {
		return prjId;
	}

	public void setPrjId(String prjId) {
		this.prjId = prjId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public String getEmpId() {
		return this.empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	public String getEmpName() {
		return empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	public String getPrjName() {
		return prjName;
	}

	public void setPrjName(String prjName) {
		this.prjName = prjName;
	}

}
