package org.sjtu.p615.entity;

// default package
// Generated 2014-9-27 21:50:52 by Hibernate Tools 3.4.0.CR1

/**
 * Planstate generated by hbm2java
 */
public class Planstate implements java.io.Serializable {

	private int stateCode;
	private String stateName;

	public Planstate() {
	}

	public Planstate(int stateCode, String stateName) {
		this.stateCode = stateCode;
		this.stateName = stateName;
	}

	public int getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(int stateCode) {
		this.stateCode = stateCode;
	}

	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

}
