package org.sjtu.p615.entity;

import java.sql.Date;
import java.util.List;

// default package
// Generated 2014-9-27 21:50:52 by Hibernate Tools 3.4.0.CR1

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	private String projectId;
	private String projectName;
	private Boolean deleteMark;
	private List<Group> groups;
	private Date startDate;
	private Date endDate;
	private String prjShortName;
	private String prjType;
	private int prjTypeId;
	private String prjSubId;
	private String contractId;
	private String inBudget;
	private String outBudget;
	private List<Role> insLeader;
	private List<Role> depLeader;
	private List<Role> prjLeader;
	private List<Role> manager;
	private String creatorID;
	public Project() {
	}

	public Project(String projectId) {
		this.projectId = projectId;
	}

	public Project(String projectId, String projectName, Boolean deleteMark) {
		this.projectId = projectId;
		this.projectName = projectName;
		this.deleteMark = deleteMark;
	}

	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public Boolean getDeleteMark() {
		return this.deleteMark;
	}

	public void setDeleteMark(Boolean deleteMark) {
		this.deleteMark = deleteMark;
	}
	public List<Group> getGroups() {
		return groups;
	}

	public void setGroups(List<Group> groups) {
		this.groups = groups;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getPrjShortName() {
		return prjShortName;
	}

	public void setPrjShortName(String prjShortName) {
		this.prjShortName = prjShortName;
	}

	public String getPrjType() {
		return prjType;
	}

	public void setPrjType(String prjType) {
		this.prjType = prjType;
	}

	public int getPrjTypeId() {
		return prjTypeId;
	}

	public void setPrjTypeId(int prjTypeId) {
		this.prjTypeId = prjTypeId;
	}

	public String getPrjSubId() {
		return prjSubId;
	}

	public void setPrjSubId(String prjSubId) {
		this.prjSubId = prjSubId;
	}

	public String getContractId() {
		return contractId;
	}

	public void setContractId(String contractId) {
		this.contractId = contractId;
	}

	public String getInBudget() {
		return inBudget;
	}

	public void setInBudget(String inBudget) {
		this.inBudget = inBudget;
	}

	public String getOutBudget() {
		return outBudget;
	}

	public void setOutBudget(String outBudget) {
		this.outBudget = outBudget;
	}

	public List<Role> getInsLeader() {
		return insLeader;
	}

	public void setInsLeader(List<Role> insLeader) {
		this.insLeader = insLeader;
	}

	public List<Role> getDepLeader() {
		return depLeader;
	}

	public void setDepLeader(List<Role> depLeader) {
		this.depLeader = depLeader;
	}

	public List<Role> getPrjLeader() {
		return prjLeader;
	}

	public void setPrjLeader(List<Role> prjLeader) {
		this.prjLeader = prjLeader;
	}

	public List<Role> getManager() {
		return manager;
	}

	public void setManager(List<Role> manager) {
		this.manager = manager;
	}

	public String getCreatorID() {
		return creatorID;
	}

	public void setCreatorID(String creatorID) {
		this.creatorID = creatorID;
	}
	
}
