package org.sjtu.p615.entity;

// default package
// Generated 2014-9-27 21:50:52 by Hibernate Tools 3.4.0.CR1

/**
 * Roleinfo generated by hbm2java
 */
public class Roleinfo implements java.io.Serializable {

	private Integer roleId;
	private String roleName;
	private Integer permissionLevel;
	private Boolean deleteMark;

	public Roleinfo() {
	}

	public Roleinfo(String roleName, Integer permissionLevel, Boolean deleteMark) {
		this.roleName = roleName;
		this.permissionLevel = permissionLevel;
		this.deleteMark = deleteMark;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Integer getPermissionLevel() {
		return this.permissionLevel;
	}

	public void setPermissionLevel(Integer permissionLevel) {
		this.permissionLevel = permissionLevel;
	}

	public Boolean getDeleteMark() {
		return this.deleteMark;
	}

	public void setDeleteMark(Boolean deleteMark) {
		this.deleteMark = deleteMark;
	}

}
