package org.sjtu.p615.entity;

// Generated 2014-9-21 11:55:16 by Hibernate Tools 3.4.0.CR1

/**
 * UserProject generated by hbm2java
 */
public class UserProject implements java.io.Serializable {

	private UserProjectId id;

	public UserProject() {
	}

	public UserProject(UserProjectId id) {
		this.id = id;
	}

	public UserProjectId getId() {
		return this.id;
	}

	public void setId(UserProjectId id) {
		this.id = id;
	}

}
