package org.sjtu.p615.entity;

// Generated 2014-10-7 14:38:33 by Hibernate Tools 3.4.0.CR1

/**
 * FailureReportMetadata generated by hbm2java
 */
public class FailureReportMetadata implements java.io.Serializable {

	private FailureReportMetadataId id;
	private String value;

	public FailureReportMetadata() {
	}

	public FailureReportMetadata(FailureReportMetadataId id) {
		this.id = id;
	}

	public FailureReportMetadata(FailureReportMetadataId id, String value) {
		this.id = id;
		this.value = value;
	}

	public FailureReportMetadataId getId() {
		return this.id;
	}

	public void setId(FailureReportMetadataId id) {
		this.id = id;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
