/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-07-28 12:26:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.DeptDataManage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class CreateFailureRport_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <title>故障报告录入</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"http://www.jeasyui.com/easyui/themes/default/easyui.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"http://www.jeasyui.com/easyui/themes/icon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"http://www.jeasyui.com/easyui/demo/demo.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-1.6.1.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://www.jeasyui.com/easyui/jquery.easyui.min.js\"></script></head>\r\n");
      out.write("<body>\r\n");
      out.write("    <h2>故障报告</h2>\r\n");
      out.write("    <p>填写故障报告基本信息并提交</p>\r\n");
      out.write("    <div style=\"margin:20px 0;\"></div>\r\n");
      out.write("    <div class=\"easyui-panel\" title=\"故障报告\" style=\"width:830px\">\r\n");
      out.write("        <div style=\"padding:10px 60px 20px 60px\">\r\n");
      out.write("        <form id=\"ff\" method=\"post\" action=\"../fracas/add.action\">\r\n");
      out.write("            <table cellpadding=\"5\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td style=\"width:160px\">故障报告编号:\r\n");
      out.write("                    <br> (Failure Report N.O)</td>          \r\n");
      out.write("                    <td><input class=\"easyui-textbox\" type=\"text\" name=\"FailureReportNum\" data-options=\"required:true\" style=\"width:160px\"></input></td>\r\n");
      out.write("                    \r\n");
      out.write("                     <td>机型:\r\n");
      out.write("                     <br> (Type)</td>          \r\n");
      out.write("                    <td><input class=\"easyui-textbox\" type=\"text\" name=\"Type\" data-options=\"required:true\" style=\"width:160px\"></input></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>故障型号:\r\n");
      out.write("                    <br>(Model)</td>\r\n");
      out.write("                    <td><input class=\"easyui-textbox\" type=\"text\" name=\"FailureModel\" data-options=\"required:true\" style=\"width:160px\"></input></td>\r\n");
      out.write("                    <td>所属系统型号:\r\n");
      out.write("                    <br>(System Type and S.N.)</td>\r\n");
      out.write("                    <td><input class=\"easyui-textbox\" type=\"text\" name=\"SystemType\" data-options=\"required:true\" style=\"width:160px\"></input></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>故障发生时间:\r\n");
      out.write("                    <br>(Time)</td>\r\n");
      out.write("                    <td><input class=\"easyui-textbox\" type=\"text\" name=\"time\" data-options=\"required:true\" style=\"width:160px\"></input></td>\r\n");
      out.write("                    <td>故障件批次号:\r\n");
      out.write("                    <br>(S.N)</td>\r\n");
      out.write("                    <td><input class=\"easyui-textbox\" type=\"text\" name=\"FailureSN\" data-options=\"required:true\" style=\"width:160px\"></input></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>故障环境条件:\r\n");
      out.write("                    <br>(Environment)</td>\r\n");
      out.write("                    <td><input class=\"easyui-textbox\" name=\"Environment\" data-options=\"required:true\" style=\"width:160px\"></input></td>\r\n");
      out.write("                     <td>故障发现人:\r\n");
      out.write("                     <br>(Reporter)</td>\r\n");
      out.write("                    <td><input class=\"easyui-textbox\" name=\"Reporter\" data-options=\"required:true\" style=\"width:160px\"></input></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>故障发生时机:\r\n");
      out.write("                    <br>(In which Process)</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                    \t<div class=\"easyui-panel\" style=\"width:210px; padding:5px\">\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"Process\"></input>环境应力筛选(ESS)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"ATP\"></input>交付试验(ATP)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"RGT\"></input>可靠性增长试验(RGT)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"TF\"></input>试用/试飞(TF)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"CT\"></input>例行试验(CT)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"RQT\"></input>可靠性鉴定试验(RQT)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"EMC\"></input>电磁兼容试验(EMC)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"PPT\"></input>电源特性试验(PPT)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"Repair\"></input>返修产品(Repair)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"Other\"></input>其他(Other)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input class=\"easyui-textbox\" name=\"content\"></input></td>\r\n");
      out.write("                    \t</div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>故障模式:\r\n");
      out.write("                    <br>(Failure Mode)</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                    \t<div class=\"easyui-panel\" style=\"width:210px; padding:5px\">\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"FailureMode\"></input>不显示(Not Display)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"ATP\"></input>不自检(no self-test)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"RGT\"></input>显示不准确(Displayed incorrect)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"TF\"></input>损坏(Damaged)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"CT\"></input>绝缘电阻下降(IR)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"RQT\"></input>短路(short circuit)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"EMC\"></input>接触不良(Poor Contact))\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"PPT\"></input>电磁敏感(EMS)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"breakdown\"></input>击穿(breakdown)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"weakSignal\"></input>信号弱(Weak Signal)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"EMI\"></input>电磁发射超标(EMI)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"Other\"></input>其他(Other)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input class=\"easyui-textbox\" name=\"othercontent\"></input></td>\r\n");
      out.write("                    \t</div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                \t<td>\r\n");
      out.write("                \t故障现象:\r\n");
      out.write("                \t<br>\r\n");
      out.write("                \t(Description)\r\n");
      out.write("                \t</td>\r\n");
      out.write("                \t<td colspan=\"2\"><input class=\"easyui-textbox\" name=\"Description\" data-options=\"multiline:true\" style=\"height:70px; width:400px\" ></input></td>\r\n");
      out.write("                \t<td>\r\n");
      out.write("                \t填表人(Sign):<input class=\"easyui-textbox\" name=\"OperatorSign\" data-options=\"required:true\" style=\"width:120px\"></input>\r\n");
      out.write("                \t<br>\r\n");
      out.write("                \t<br>\r\n");
      out.write("                \t日期(Date):<input class=\"easyui-datebox textbox\" name=\"OperatorSignDate\">\r\n");
      out.write("                \t</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                \t<td>\r\n");
      out.write("                \t项目/技术负责人:\r\n");
      out.write("                \t<br>\r\n");
      out.write("                \t(Technical Leader)\r\n");
      out.write("                \t</td>\r\n");
      out.write("                \t<td colspan=\"3\"><input class=\"easyui-textbox\" name=\"TechnicalLeaderOpinion\" data-options=\"multiline:true\" style=\"height:70px; width:400px\" ></input></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>质量问题性质:\r\n");
      out.write("                    <br>(Quality Issue Category)</td>\r\n");
      out.write("                    <td  colspan=\"3\">\r\n");
      out.write("                    \t<div class=\"easyui-panel\" style=\"padding:5px\">\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"QualityIssueCategory\"></input>一般质量问题(General)\r\n");
      out.write("                    \t\t\t\t&nbsp\r\n");
      out.write("                    \t\t\t\t&nbsp\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"ATP\"></input>重复质量问题(Repetitive)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"RGT\"></input>严重质量问题(Serious)\r\n");
      out.write("                    \t\t\t\t&nbsp\r\n");
      out.write("                    \t\t\t\t&nbsp\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"TF\"></input>重大质量问题(Significant)\r\n");
      out.write("                    \t\t\t\t<br>\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"CT\"></input>FRACAS\r\n");
      out.write("                    \t\t\t\t&nbsp\r\n");
      out.write("                    \t\t\t\t&nbsp\r\n");
      out.write("                    \t\t\t\t&nbsp\r\n");
      out.write("                    \t\t\t\t&nbsp\r\n");
      out.write("                    \t\t\t\t&nbsp\r\n");
      out.write("                    \t\t\t\t&nbsp\r\n");
      out.write("                    \t\t\t\t&nbsp\r\n");
      out.write("                    \t\t\t\t&nbsp\r\n");
      out.write("                    \t\t\t\t&nbsp\r\n");
      out.write("                    \t\t\t\t&nbsp\r\n");
      out.write("                    \t\t\t\t&nbsp\r\n");
      out.write("                    \t\t\t\t&nbsp\r\n");
      out.write("                    \t\t\t\t<input type=\"checkbox\" name=\"RQT\"></input>双五归零(Dou-5)\r\n");
      out.write("                    \t</div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                \t<td>\r\n");
      out.write("                \t故障审查委员会意见:\r\n");
      out.write("                \t<br>\r\n");
      out.write("                \t(MRB)\r\n");
      out.write("                \t</td>\r\n");
      out.write("                \t<td colspan=\"2\"><input class=\"easyui-textbox\" name=\"Mrb\" data-options=\"multiline:true\" style=\"height:70px; width:400px\" ></input></td>\r\n");
      out.write("                \t<td>\r\n");
      out.write("                \t签署(Sign):<input class=\"easyui-textbox\" name=\"CommtiteeSign\" data-options=\"required:true\"></input>\r\n");
      out.write("                \t<br>\r\n");
      out.write("                \t<br>\r\n");
      out.write("                \t日期(Date):<input class=\"easyui-datebox textbox\" name=\"CommitteeSignDate\">\r\n");
      out.write("                \t</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            <input type=\"submit\" value=\"value\"/>\r\n");
      out.write("        </form>\r\n");
      out.write("        <div style=\"text-align:center;padding:5px\">\r\n");
      out.write("            <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"submitForm()\">Submit</a>\r\n");
      out.write("            <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"clearForm()\">Clear</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("        function submitForm(){\r\n");
      out.write("            $('#ff').form('submit');\r\n");
      out.write("        }\r\n");
      out.write("        function clearForm(){\r\n");
      out.write("            $('#ff').form('clear');\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
