package org.sjtu.p615.entity;

// Generated 2015-7-15 9:19:31 by Hibernate Tools 3.4.0.CR1

import java.sql.Date;

/**
 * Plan generated by hbm2java
 */
public class Plan implements java.io.Serializable {

	private Integer planKey;
	private Integer parentKey;
	private String parentPlanCode;
	private String projectId;
	private String projectName;
	private String planCode;
	private String planSerialNumber;
	private String planName;
	private Date planIssuedDate;
	private Date planDeadlineDate;
	private Date planStartDate;
	private Date planFinishDate;
	private String planSource;
	private String employeeId;
	private String planController;
	private String planControllerId;
	private String planCreatorId;
	private String planAuditorId;
	private String employeeName;
	private Integer planStateCode;
	private Boolean back;
	private String reviewer;
	private Boolean leaf;
	private Integer level;
	private String changeDetail;
	private Boolean complete;
	private Boolean accept;
	private Boolean issue;
	private Boolean deleteMark;
	private String planType;
	private Double savic;
	private Double comac;
	private Double spi;
	private Double completePercentage;
	private String remainingDuration;
	private String remainingHour;
	private String remainingPeriod;
	private Date baselineFinishTime;
	private Date baselineStartTime;
	private String predecessor;
	private String successor;
	private String taskContent;
	private Double taskWeight;
	private String controlDepartmentId;
	private String controlDepartment;
	private String groupId;
	private String groupName;
	private Double budget;
	private String cashFlow;
	private String cashSource;
	private String cashSubject;
	private Double cashReal;
	private Boolean isTask;
	private String wbs;
	private Integer planRemainingDate;

	public Plan() {
	}

	public Plan(String planCode) {
		this.planCode = planCode;
	}

	public Plan(Integer parentKey, String parentPlanCode, String projectId,
			String projectName, String planCode, String planSerialNumber,
			String planName, Date planIssuedDate, Date planDeadlineDate,
			Date planStartDate, Date planFinishDate, String planSource,
			String employeeId, String planController, String planControllerId,
			String planCreatorId, String planAuditorId, String employeeName,
			Integer planStateCode, Boolean back, String reviewer, Boolean leaf,
			Integer level, String changeDetail, Boolean complete,
			Boolean accept, Boolean issue, Boolean deleteMark, String planType,
			Double savic, Double comac, Double spi, Double completePercentage,
			String remainingDuration, String remainingHour,
			String remainingPeriod, Date baselineFinishTime,
			Date baselineStartTime, String predecessor, String successor,
			String taskContent, Double taskWeight, String controlDepartmentId,
			String controlDepartment, String groupId, String groupName,
			Double budget, String cashFlow, String cashSource,
			String cashSubject, Double cashReal, Boolean isTask, String wbs) {
		this.parentKey = parentKey;
		this.parentPlanCode = parentPlanCode;
		this.projectId = projectId;
		this.projectName = projectName;
		this.planCode = planCode;
		this.planSerialNumber = planSerialNumber;
		this.planName = planName;
		this.planIssuedDate = planIssuedDate;
		this.planDeadlineDate = planDeadlineDate;
		this.planStartDate = planStartDate;
		this.planFinishDate = planFinishDate;
		this.planSource = planSource;
		this.employeeId = employeeId;
		this.planController = planController;
		this.planControllerId = planControllerId;
		this.planCreatorId = planCreatorId;
		this.planAuditorId = planAuditorId;
		this.employeeName = employeeName;
		this.planStateCode = planStateCode;
		this.back = back;
		this.reviewer = reviewer;
		this.leaf = leaf;
		this.level = level;
		this.changeDetail = changeDetail;
		this.complete = complete;
		this.accept = accept;
		this.issue = issue;
		this.deleteMark = deleteMark;
		this.planType = planType;
		this.savic = savic;
		this.comac = comac;
		this.spi = spi;
		this.completePercentage = completePercentage;
		this.remainingDuration = remainingDuration;
		this.remainingHour = remainingHour;
		this.remainingPeriod = remainingPeriod;
		this.baselineFinishTime = baselineFinishTime;
		this.baselineStartTime = baselineStartTime;
		this.predecessor = predecessor;
		this.successor = successor;
		this.taskContent = taskContent;
		this.taskWeight = taskWeight;
		this.controlDepartmentId = controlDepartmentId;
		this.controlDepartment = controlDepartment;
		this.groupId = groupId;
		this.groupName = groupName;
		this.budget = budget;
		this.cashFlow = cashFlow;
		this.cashSource = cashSource;
		this.cashSubject = cashSubject;
		this.cashReal = cashReal;
		this.isTask = isTask;
		this.wbs = wbs;
	}

	public Integer getPlanKey() {
		return this.planKey;
	}

	public void setPlanKey(Integer planKey) {
		this.planKey = planKey;
	}

	public Integer getParentKey() {
		return this.parentKey;
	}

	public void setParentKey(Integer parentKey) {
		this.parentKey = parentKey;
	}

	public String getParentPlanCode() {
		return this.parentPlanCode;
	}

	public void setParentPlanCode(String parentPlanCode) {
		this.parentPlanCode = parentPlanCode;
	}

	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getPlanCode() {
		return this.planCode;
	}

	public void setPlanCode(String planCode) {
		this.planCode = planCode;
	}

	public String getPlanSerialNumber() {
		return this.planSerialNumber;
	}

	public void setPlanSerialNumber(String planSerialNumber) {
		this.planSerialNumber = planSerialNumber;
	}

	public String getPlanName() {
		return this.planName;
	}

	public void setPlanName(String planName) {
		this.planName = planName;
	}

	public Date getPlanIssuedDate() {
		return this.planIssuedDate;
	}

	public void setPlanIssuedDate(Date planIssuedDate) {
		this.planIssuedDate = planIssuedDate;
	}

	public Date getPlanDeadlineDate() {
		return this.planDeadlineDate;
	}

	public void setPlanDeadlineDate(Date planDeadlineDate) {
		this.planDeadlineDate = planDeadlineDate;
	}

	public Date getPlanStartDate() {
		return this.planStartDate;
	}

	public void setPlanStartDate(Date planStartDate) {
		this.planStartDate = planStartDate;
	}

	public Date getPlanFinishDate() {
		return this.planFinishDate;
	}

	public void setPlanFinishDate(Date planFinishDate) {
		this.planFinishDate = planFinishDate;
	}

	public String getPlanSource() {
		return this.planSource;
	}

	public void setPlanSource(String planSource) {
		this.planSource = planSource;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public String getPlanController() {
		return this.planController;
	}

	public void setPlanController(String planController) {
		this.planController = planController;
	}

	public String getPlanControllerId() {
		return this.planControllerId;
	}

	public void setPlanControllerId(String planControllerId) {
		this.planControllerId = planControllerId;
	}

	public String getPlanCreatorId() {
		return this.planCreatorId;
	}

	public void setPlanCreatorId(String planCreatorId) {
		this.planCreatorId = planCreatorId;
	}

	public String getPlanAuditorId() {
		return this.planAuditorId;
	}

	public void setPlanAuditorId(String planAuditorId) {
		this.planAuditorId = planAuditorId;
	}

	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public Integer getPlanStateCode() {
		return this.planStateCode;
	}

	public void setPlanStateCode(Integer planStateCode) {
		this.planStateCode = planStateCode;
	}

	public Boolean getBack() {
		return this.back;
	}

	public void setBack(Boolean back) {
		this.back = back;
	}

	public String getReviewer() {
		return this.reviewer;
	}

	public void setReviewer(String reviewer) {
		this.reviewer = reviewer;
	}

	public Boolean getLeaf() {
		return this.leaf;
	}

	public void setLeaf(Boolean leaf) {
		this.leaf = leaf;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public String getChangeDetail() {
		return this.changeDetail;
	}

	public void setChangeDetail(String changeDetail) {
		this.changeDetail = changeDetail;
	}

	public Boolean getComplete() {
		return this.complete;
	}

	public void setComplete(Boolean complete) {
		this.complete = complete;
	}

	public Boolean getAccept() {
		return this.accept;
	}

	public void setAccept(Boolean accept) {
		this.accept = accept;
	}

	public Boolean getIssue() {
		return this.issue;
	}

	public void setIssue(Boolean issue) {
		this.issue = issue;
	}

	public Boolean getDeleteMark() {
		return this.deleteMark;
	}

	public void setDeleteMark(Boolean deleteMark) {
		this.deleteMark = deleteMark;
	}

	public String getPlanType() {
		return this.planType;
	}

	public void setPlanType(String planType) {
		this.planType = planType;
	}

	public Double getSavic() {
		return this.savic;
	}

	public void setSavic(Double savic) {
		this.savic = savic;
	}

	public Double getComac() {
		return this.comac;
	}

	public void setComac(Double comac) {
		this.comac = comac;
	}

	public Double getSpi() {
		return this.spi;
	}

	public void setSpi(Double spi) {
		this.spi = spi;
	}

	public Double getCompletePercentage() {
		return this.completePercentage;
	}

	public void setCompletePercentage(Double completePercentage) {
		this.completePercentage = completePercentage;
	}

	public String getRemainingDuration() {
		return this.remainingDuration;
	}

	public void setRemainingDuration(String remainingDuration) {
		this.remainingDuration = remainingDuration;
	}

	public String getRemainingHour() {
		return this.remainingHour;
	}

	public void setRemainingHour(String remainingHour) {
		this.remainingHour = remainingHour;
	}

	public String getRemainingPeriod() {
		return this.remainingPeriod;
	}

	public void setRemainingPeriod(String remainingPeriod) {
		this.remainingPeriod = remainingPeriod;
	}

	public Date getBaselineFinishTime() {
		return this.baselineFinishTime;
	}

	public void setBaselineFinishTime(Date baselineFinishTime) {
		this.baselineFinishTime = baselineFinishTime;
	}

	public Date getBaselineStartTime() {
		return this.baselineStartTime;
	}

	public void setBaselineStartTime(Date baselineStartTime) {
		this.baselineStartTime = baselineStartTime;
	}

	public String getPredecessor() {
		return this.predecessor;
	}

	public void setPredecessor(String predecessor) {
		this.predecessor = predecessor;
	}

	public String getSuccessor() {
		return this.successor;
	}

	public void setSuccessor(String successor) {
		this.successor = successor;
	}

	public String getTaskContent() {
		return this.taskContent;
	}

	public void setTaskContent(String taskContent) {
		this.taskContent = taskContent;
	}

	public Double getTaskWeight() {
		return this.taskWeight;
	}

	public void setTaskWeight(Double taskWeight) {
		this.taskWeight = taskWeight;
	}

	public String getControlDepartmentId() {
		return this.controlDepartmentId;
	}

	public void setControlDepartmentId(String controlDepartmentId) {
		this.controlDepartmentId = controlDepartmentId;
	}

	public String getControlDepartment() {
		return this.controlDepartment;
	}

	public void setControlDepartment(String controlDepartment) {
		this.controlDepartment = controlDepartment;
	}

	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public Double getBudget() {
		return this.budget;
	}

	public void setBudget(Double budget) {
		this.budget = budget;
	}

	public String getCashFlow() {
		return this.cashFlow;
	}

	public void setCashFlow(String cashFlow) {
		this.cashFlow = cashFlow;
	}

	public String getCashSource() {
		return this.cashSource;
	}

	public void setCashSource(String cashSource) {
		this.cashSource = cashSource;
	}

	public String getCashSubject() {
		return this.cashSubject;
	}

	public void setCashSubject(String cashSubject) {
		this.cashSubject = cashSubject;
	}

	public Double getCashReal() {
		return this.cashReal;
	}

	public void setCashReal(Double cashReal) {
		this.cashReal = cashReal;
	}

	public Boolean getIsTask() {
		return this.isTask;
	}

	public void setIsTask(Boolean isTask) {
		this.isTask = isTask;
	}

	public String getWbs() {
		return this.wbs;
	}

	public void setWbs(String wbs) {
		this.wbs = wbs;
	}

	public Integer getPlanRemainingDate() {
		return planRemainingDate;
	}

	public void setPlanRemainingDate(Integer planRemainingDate) {
		this.planRemainingDate = planRemainingDate;
	}

}
