package org.sjtu.p615.entity;

// Generated 2014-10-7 14:38:33 by Hibernate Tools 3.4.0.CR1

/**
 * FailureReportMetadataId generated by hbm2java
 */
public class FailureReportMetadataId implements java.io.Serializable {

	private String projectName;
	private String type;

	public FailureReportMetadataId() {
	}

	public FailureReportMetadataId(String projectName, String type) {
		this.projectName = projectName;
		this.type = type;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FailureReportMetadataId))
			return false;
		FailureReportMetadataId castOther = (FailureReportMetadataId) other;

		return ((this.getProjectName() == castOther.getProjectName()) || (this
				.getProjectName() != null && castOther.getProjectName() != null && this
				.getProjectName().equals(castOther.getProjectName())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null
						&& castOther.getType() != null && this.getType()
						.equals(castOther.getType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getProjectName() == null ? 0 : this.getProjectName()
						.hashCode());
		result = 37 * result
				+ (getType() == null ? 0 : this.getType().hashCode());
		return result;
	}

}
