package org.sjtu.p615.entity;
// Generated 2015-9-29 15:04:58 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

	private Integer messageId;
	private String messageType;
	private String messageContent;
	private String projectId;
	private String prjShortName;
	private String planCode;
	private Boolean isPackageDir;
	private String actionId;
	private Boolean isActionDir;
	private String messageSource;
	private Date messageDate;
	private String employeeId;
	private Integer noticeId;
	private Boolean deleteMark;

	public Message() {
	}

	public Message(String messageType, String messageContent, String projectId,
			String prjShortName, String planCode, Boolean isPackageDir,
			String actionId, Boolean isActionDir, String messageSource,
			Date messageDate, String employeeId, Integer noticeId,
			Boolean deleteMark) {
		this.messageType = messageType;
		this.messageContent = messageContent;
		this.projectId = projectId;
		this.prjShortName = prjShortName;
		this.planCode = planCode;
		this.isPackageDir = isPackageDir;
		this.actionId = actionId;
		this.isActionDir = isActionDir;
		this.messageSource = messageSource;
		this.messageDate = messageDate;
		this.employeeId = employeeId;
		this.noticeId = noticeId;
		this.deleteMark = deleteMark;
	}

	public Integer getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	public String getMessageType() {
		return this.messageType;
	}

	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}

	public String getMessageContent() {
		return this.messageContent;
	}

	public void setMessageContent(String messageContent) {
		this.messageContent = messageContent;
	}

	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	public String getPrjShortName() {
		return this.prjShortName;
	}

	public void setPrjShortName(String prjShortName) {
		this.prjShortName = prjShortName;
	}

	public String getPlanCode() {
		return this.planCode;
	}

	public void setPlanCode(String planCode) {
		this.planCode = planCode;
	}

	public Boolean getIsPackageDir() {
		return this.isPackageDir;
	}

	public void setIsPackageDir(Boolean isPackageDir) {
		this.isPackageDir = isPackageDir;
	}

	public String getActionId() {
		return this.actionId;
	}

	public void setActionId(String actionId) {
		this.actionId = actionId;
	}

	public Boolean getIsActionDir() {
		return this.isActionDir;
	}

	public void setIsActionDir(Boolean isActionDir) {
		this.isActionDir = isActionDir;
	}

	public String getMessageSource() {
		return this.messageSource;
	}

	public void setMessageSource(String messageSource) {
		this.messageSource = messageSource;
	}

	public Date getMessageDate() {
		return this.messageDate;
	}

	public void setMessageDate(Date messageDate) {
		this.messageDate = messageDate;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public Integer getNoticeId() {
		return this.noticeId;
	}

	public void setNoticeId(Integer noticeId) {
		this.noticeId = noticeId;
	}

	public Boolean getDeleteMark() {
		return this.deleteMark;
	}

	public void setDeleteMark(Boolean deleteMark) {
		this.deleteMark = deleteMark;
	}

}
